name: ci

on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Enable tmate debug"
        type: boolean
        default: "false"

jobs:
  check-semantic-version:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: octue/check-semantic-version@1.0.0.beta-9
        with:
          path: pyproject.toml
          breaking_change_indicated_by: minor
